### ISSUE TITLE
Create new carousel for product pages

### ISSUE THREAD

**Issue by roaddust2** [roaddust2/wait-web#5]
**Task:**
Create new carousel for product pages, currently default Bootstrap 5 carousel is used.

**Requirements:**
1. It should contain square images from backend (already square, no need to crop)
2. On the right side there should be 4 fixed thumbnails, if there are more images, scroll should be added
3. Arrows to switch images (add loop)
4. No autoswitch
5. By click on the image, open modal and increase image size (can use bootstrap modals or custom)

**Example:**
![example](https://github.com/roaddust2/wait-web/assets/42116054/43307ff8-14c1-450b-8ccb-2b308b8da09c)

**Comment by DebanganMishra40** [comment]
I would like to work on this, could you please allow me to do so?

**Comment by roaddust2** [comment]
@DebanganMishra40 I’m glad you are interested in contributing to my project, unfortunately this issue is already taken by another user

**Comment by DebanganMishra40** [comment]
Noted
